apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
  labels:
    app: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
        - name: tasky
          image: "${IMAGE}"
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: tasky-secret
                  key: MONGO_URI
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: tasky-secret
                  key: MONGO_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tasky-secret
                  key: SECRET_KEY
