apiVersion: v1
kind: Secret
metadata:
  name: tasky-secrets
  namespace: tasky
type: Opaque
stringData:
  # Replace with your actual values:
  MONGODB_URI: "mongodb://admin:goodlab@10.0.0.199:27017/tasky?authSource=admin"
  SECRET_KEY: "43a8230cd9df03bfc03f4cda39d9427a1c4a46cb0190e9864042a4933debc55c"
